name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        file: ./final project/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_TOKEN }}/final-project:latest
#    - name: Build the Docker image
#      run: cd final\ project && docker build . --file Dockerfile --tag final-project:$(date +%s)
